### ISSUE TITLE
getCell, getRow, getColumn

### ISSUE THREAD

**Issue by KorkhovPavel** [PerfecXX/MicroPython-GoogleSheet#1]
Hi. 
Good soft, but function getCell, getRow, getColumn show empty value, because byte code comes from the server.

with these changes everything works:
ggsheet.py in getCell, getRow, getColumn:
```
        if responseCode > 0:
            html_code = response.text
            start_index = html_code.find('start')
            end_index = html_code.find('finish')
            script_content = html_code[start_index:end_index]
            return script_content[29:-24]
        else:
            return "Error Code:{}".format(responseCode)
```
script.gs in getCell, getRow, getColumn:
`<body><h1>start</h1><h1>" + value + "</h1><h1>finish</h1></body>`

Have a good day.

**Comment by PerfecXX** [comment]
Your provided code in ggsheet.py is fine and working so far.

```python
if responseCode > 0:
            html_code = response.text
            start_index = html_code.find('start')
            end_index = html_code.find('finish')
            script_content = html_code[start_index:end_index]
            return script_content[29:-24]
        else:
            return "Error Code:{}".format(responseCode)
```

however the following code only working with the **getCell** mode in script.gs
```html
<body><h1>start</h1><h1>" + value + "</h1><h1>finish</h1></body>

```

In the fact that getRow and getColumn modes in script.gs are using loops to concatenate the string and store it in a different variable named _**heading**_,  the code in both modes should be like this:

```html
var html = "<html><head><title>Get Column Data</title></head><body><h1>start</h1><h1>" + heading + "</h1><h1>finish</h1></body></html>";

```

```html
var html = "<html><head><title>Get Row Data</title></head><body><h1>start</h1><h1>" + heading + "</h1><h1>finish</h1></body></html>";

```

The next patch will release soon. 
Thank you for opening this issue.
